FROM node:20-alpine

# 1. Instalar pnpm globalmente en el contenedor
RUN npm install -g pnpm

WORKDIR /app

# 2. Copiar los archivos de configuración de dependencias

COPY package*.json tsconfig.json pnpm-lock.yaml* ./

# 3. Instalar dependencias de forma estricta y rápida
RUN pnpm install --frozen-lockfile

# 4. Copiar el código fuente y compilar
COPY src ./src
RUN pnpm run build

# 5. Comando de arranque
CMD ["pnpm", "run", "start"]